//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/*
		WARNING!
		
        TO PROPERLY TEST THE APP FUNCTIONALITY AND CONNECT TO DB, PLEASE RESTORE DB FROM .BAK FILE AND IMPORT DATA BY EXECUTING .SQL FILE 
		
		BOTH PRESENT IN "/DATABASE" DIRECTORY,
		
		THEN PROVIDE PROPER CONNECTION STRING VALUES IN FOLLOWING FILES:
		
		-SETTINGS.DESIGNER.CS (HERE, IN "DefaultSettingValueAttribute" FIELD)
		
		-SETTINGS.SETTINGS
		
		-APP.CONFIG
 */

namespace Biblioteka.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=;Initial Catalog=;User ID=;Password=")]
        public string db_a8b501_bibliotekaConnectionString {
            get {
                return ((string)(this["db_a8b501_bibliotekaConnectionString"]));
            }
        }
    }
}
